mode = "dark"
accent = "#6858A8"
selection = "#181428"
muted = "#4A4868"
background = "#0E0A16"
dark_background = "#080610"
darker_background = "#040308"
lighter_background = "#181428"
foreground = "#D8D4E8"
dark_foreground = "#787088"
light_foreground = "#E4DCEC"
bright_foreground = "#FFFFFF"
magenta = "#6858A8"
cyan = "#586898"
blue = "#4858A8"
green = "#486878"
red = "#884868"
yellow = "#888858"
orange = "#785848"
brown = "#281838"
bright_magenta = "#8878C8"
bright_cyan = "#7888B8"
bright_blue = "#6878C8"
bright_green = "#688898"
bright_red = "#A86888"
bright_yellow = "#A8A878"
