mode = "dark"
accent = "#6A3A5A"
selection = "#160E18"
muted = "#4A3A4A"
background = "#0A060C"
dark_background = "#060306"
darker_background = "#030103"
lighter_background = "#160E18"
foreground = "#D0C8D0"
dark_foreground = "#786078"
light_foreground = "#Dcd4Dc"
bright_foreground = "#FFFFFF"
magenta = "#6A3A5A"
cyan = "#5A4A5A"
blue = "#4A3A5A"
green = "#4A5A4A"
red = "#8A3A4A"
yellow = "#8A6A3A"
orange = "#6A4A3A"
brown = "#2A1422"
bright_magenta = "#8A5A7A"
bright_cyan = "#7A6A7A"
bright_blue = "#6A5A7A"
bright_green = "#6A7A6A"
bright_red = "#A85A5A"
bright_yellow = "#A88858"
