mode = "dark"
accent = "#C04878"
selection = "#241828"
muted = "#6A4860"
background = "#160E16"
dark_background = "#100810"
darker_background = "#080408"
lighter_background = "#241828"
foreground = "#E8D8E0"
dark_foreground = "#987088"
light_foreground = "#F0E0E8"
bright_foreground = "#FFFFFF"
magenta = "#C04878"
cyan = "#A05868"
blue = "#884858"
green = "#885868"
red = "#C83848"
yellow = "#C07848"
orange = "#B05838"
brown = "#3A1828"
bright_magenta = "#D86898"
bright_cyan = "#B87888"
bright_blue = "#A06878"
bright_green = "#A07888"
bright_red = "#E05868"
bright_yellow = "#E09868"
