mode = "dark"
accent = "#4A3A78"
selection = "#140E1E"
muted = "#3A3858"
background = "#080610"
dark_background = "#050308"
darker_background = "#020104"
lighter_background = "#140E1E"
foreground = "#D0CCDC"
dark_foreground = "#686078"
light_foreground = "#DCD4E4"
bright_foreground = "#FFFFFF"
magenta = "#4A3A78"
cyan = "#3A4868"
blue = "#2A3878"
green = "#2A4858"
red = "#683848"
yellow = "#686838"
orange = "#584838"
brown = "#1E1428"
bright_magenta = "#6A5A98"
bright_cyan = "#5A6888"
bright_blue = "#4A58A8"
bright_green = "#4A6888"
bright_red = "#885868"
bright_yellow = "#888858"
